apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: sdp-demo-388112
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-auth
      key: creds
